---
- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
    state: present
    filename: docker-ce
  when: ansible_os_family == 'Debian'

- name: Add Docker repository
  yum_repository:
    baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
    name: Docker CE
    description: Docker CE Repository
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
    state: present
  when: ansible_os_family == 'RedHat'
